/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhchatserver;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class HHFrame extends javax.swing.JFrame implements HHServer.UiListener {

    private HHServer server;
    
    /**
     * Creates new form TestFrame
     */
    public HHFrame() {
        initComponents();
        initViews();
    }
    
    private void initViews() {
        try {
            InetAddress inetAddress = InetAddress.getLocalHost();
            String host = inetAddress.getHostAddress();
            lblHostValue.setText(host);
        } catch (UnknownHostException e) {
            btnLaunch.setEnabled(false);
            taState.append("找不到本机ip\n");
        }
    }
    
    @Override
    public void onStateChanged(String detail) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                taState.append(detail + "\n");
            }
        });
    }
    
    @Override
    public void onLaunchSucceed(String detail) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                taState.append(detail + "\n");
                btnStop.setEnabled(true);
                tfPortValue.setEditable(false);
                lblStateValue.setText("运行中");
                panelLight.setBackground(Color.GREEN);
            }
        });
    }
    
    @Override
    public void onLaunchFail(String detail) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                btnLaunch.setEnabled(true);
                taState.append(detail + "\n");
                lblStateValue.setText("未启动");
                panelLight.setBackground(Color.RED);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lblHostValue = new javax.swing.JLabel();
        tfPortValue = new javax.swing.JTextField();
        btnLaunch = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taState = new javax.swing.JTextArea();
        lblStateValue = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        panelLight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HHchat服务端");
        setResizable(false);

        lblHost.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lblHost.setText("本机ip：");

        lblPort.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lblPort.setText("端口号：");

        lblHostValue.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        tfPortValue.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        tfPortValue.setText("2333");

        btnLaunch.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnLaunch.setText("启动");
        btnLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaunchActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnStop.setText("停止");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        taState.setColumns(20);
        taState.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        taState.setRows(5);
        jScrollPane1.setViewportView(taState);

        lblStateValue.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lblStateValue.setText("未启动");

        lblState.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        lblState.setText("运行状态:");

        panelLight.setBackground(new java.awt.Color(255, 0, 0));
        panelLight.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout panelLightLayout = new javax.swing.GroupLayout(panelLight);
        panelLight.setLayout(panelLightLayout);
        panelLightLayout.setHorizontalGroup(
            panelLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        panelLightLayout.setVerticalGroup(
            panelLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPortValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLaunch)
                            .addComponent(btnStop))))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblHost)
                    .addComponent(lblHostValue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(btnLaunch))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfPortValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort)
                    .addComponent(lblStateValue)
                    .addComponent(panelLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchActionPerformed
        // TODO add your handling code here:
        
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                taState.setText("");
                btnLaunch.setEnabled(false);
                lblStateValue.setText("启动中");
                panelLight.setBackground(Color.YELLOW);
            }
        });
        new Thread(new Runnable() {
            @Override
            public void run() {
                server = HHServer.getInstance(HHFrame.this, 2333);
                server.launch();
            }
        }).start();
        
    }//GEN-LAST:event_btnLaunchActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        server.stop();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                btnLaunch.setEnabled(true);
                btnStop.setEnabled(false);
                tfPortValue.setEditable(true);
                lblStateValue.setText("未启动");
                panelLight.setBackground(Color.RED);
            }
        });
        
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HHFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaunch;
    private javax.swing.JButton btnStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblHostValue;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateValue;
    private javax.swing.JPanel panelLight;
    private javax.swing.JTextArea taState;
    private javax.swing.JTextField tfPortValue;
    // End of variables declaration//GEN-END:variables
}
